[tool.aerich]
tortoise_orm = "app.core.database.TORTOISE_ORM"
location = "./app/db/migrations"
src_folder = "./."

[tool.poetry]
name = "project"
version = "1.0.0"
description = "For Python FastAPI Project!"
authors = ["Sameer <sameershaik34767@gmail.com>"]